from __future__ import annotations

from typing import Iterable, List, Protocol
from git_mind.domain.github import PullRequest, ReviewThread


class GitHubPort(Protocol):
    def list_open_prs(self) -> List[PullRequest]: ...
    def iter_review_threads(self, pr_number: int) -> Iterable[ReviewThread]: ...
    def post_reply(self, thread_id: str, body: str) -> bool: ...
    def resolve_thread(self, thread_id: str) -> bool: ...

