from __future__ import annotations

from typing import Dict, Optional, Protocol, List


class MindBackend(Protocol):
    def head(self, session: Optional[str]) -> Optional[str]: ...
    def write_snapshot(self, *, session: Optional[str], state: Dict, op: str, args: Dict | None, result: str) -> str: ...
    def read_state(self, *, session: Optional[str]) -> Dict: ...
    def is_worktree_clean(self) -> bool: ...
    def nuke_refs(self, prefix: str = "refs/mind/") -> List[str]: ...

