from __future__ import annotations
from typing import Protocol, Optional, Mapping, Any

class ConfigPort(Protocol):
    @property
    def path(self): ...
    def read(self) -> Mapping[str, Any]: ...
    def write(self, data: Mapping[str, Any]) -> None: ...
