from __future__ import annotations
from typing import Protocol

class GitPort(Protocol):
    def is_commit(self, sha: str) -> bool: ...
    def current_branch(self) -> str: ...
    def has_upstream(self) -> bool: ...
    def push(self) -> bool: ...
    def push_set_upstream(self, remote: str, upstream_ref: str) -> bool: ...
    def add_and_commit(self, paths: list[str], message: str) -> bool: ...
    def head_sha(self) -> str: ...
